# -*- coding: utf-8 -*-
"""Corona_tweets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jxfmn48Hl2HalVjFvjIC-5MfFVL4g0YC

From Kaggle: This dataset contains the Tweets of users who have applied the following hashtags: #coronavirus, #coronavirusoutbreak, #coronavirusPandemic, #covid19, #covid_19

From about 17 March, the dataset also included the following additional hashtags: #epitwitter, #ihavecorona

# Data Dictionary

**status_id**: The ID of the actual Tweet.  
**user_id**: The ID of the user account that Tweeted.  
**created_at**: The date and time of the Tweet.  
**screen_name**: The screen name of the account that Tweeted.  
**text**: The text of the Tweet.  
**source**: The type of app used.  
**reply_to_status_id**: The ID of the Tweet to which this was a reply.  
**reply_to_user_id**: The ID of the user to whom this Tweet was a reply.  
**reply_to_screen_name**: The screen name of the user to whom this Tweet was a reply.  
**is_quote**: Whether this Tweet is a quote of another Tweet.  
**is_retweet**: Whether this Tweet is a retweet.  
**favourites_count**: The number of favourites this Tweet has received.  
**retweet_count**: The number of times this Tweet has been retweeted.  
**country_code**: The country code of the account that Tweeted.  
**place_full_name**: The name of the place of the account that Tweeted.  
**place_type**: A description of the type of place corresponding with place_full_name.  
**followers_count**: The number of followers of the account that Tweeted.  
**friends_count**: The number of friends of the account that Tweeted.  
**account_lang**: The language of the account that Tweeted.  
**account_created_at**: The date and time that the account that Tweeted was created.  
**verified**: Whether the account that Tweeted is verified.  
**lang**: The language of the Tweet.

# Data Exploration + Cleanup
"""

from time import sleep
import csv

import pandas as pd
import numpy as np 
import pandas as pd
import seaborn as sns
import glob
import json
import matplotlib.pyplot as plt

path = '/content/drive/My Drive/Unstructured Project/corona_tweets304.CSV'
corona_tweets = pd.read_csv(path)

corona_tweets.head()

corona_tweets.shape

print(len(corona_tweets['created_at'].unique()))

print(len(corona_tweets['screen_name'].unique()))
print(len(corona_tweets['source'].unique()))
print(len(corona_tweets['reply_to_status_id'].unique()))
print(len(corona_tweets['reply_to_user_id'].unique()))
print(len(corona_tweets['reply_to_screen_name'].unique()))
print(len(corona_tweets['country_code'].unique()))
print(len(corona_tweets['place_full_name'].unique()))
print(len(corona_tweets['place_type'].unique()))
print(len(corona_tweets['account_lang'].unique()))
print(len(corona_tweets['lang'].unique()))

#we'll have to pull out en tweets only

corona_tweets['lang'].unique()

corona_tweets = corona_tweets.drop(['account_lang'], axis=1)







from google.colab import drive
drive.mount('/content/drive')

"""Code To Get Data Combined. You don't need to run this!! I just wanted you to see the process and know that it was sound!"""

premarch = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-00 Coronavirus Tweets (pre 2020-03-12).CSV'
pre_march = pd.read_csv(premarch)

marchonetwo = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-12 Coronavirus Tweets.CSV'
marchone_two = pd.read_csv(marchonetwo)

marchonethree = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-13 Coronavirus Tweets.CSV'
marchone_three = pd.read_csv(marchonethree)

marchonefour = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-14 Coronavirus Tweets.CSV'
marchone_four = pd.read_csv(marchonefour)

marchonefive = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-15 Coronavirus Tweets.CSV'
marchone_five = pd.read_csv(marchonefive)

marchonesix = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-16 Coronavirus Tweets.CSV'
marchone_six = pd.read_csv(marchonesix)

marchoneseven = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-17 Coronavirus Tweets.CSV'
marchone_seven = pd.read_csv(marchoneseven)

marchoneeight = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-18 Coronavirus Tweets.CSV'
marchone_eight= pd.read_csv(marchoneeight)

marchonenine = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-19 Coronavirus Tweets.CSV'
marchone_nine = pd.read_csv(marchonenine)

marchtwozero= '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-20 Coronavirus Tweets.CSV'
marchtwo_zero = pd.read_csv(marchtwozero)

marchtwoone= '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-21 Coronavirus Tweets.CSV'
marchtwo_one = pd.read_csv(marchtwoone)

marchtwotwo= '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-22 Coronavirus Tweets.CSV'
marchtwo_two = pd.read_csv(marchtwotwo)

marchtwothree = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-23 Coronavirus Tweets.CSV'
marchtwo_three = pd.read_csv(marchtwothree)

marchtwofour = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-24 Coronavirus Tweets.CSV'
marchtwo_four = pd.read_csv(marchtwofour)

marchtwofive= '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-25 Coronavirus Tweets.CSV'
marchtwo_five = pd.read_csv(marchtwofive)

marchtwosix= '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-26 Coronavirus Tweets.CSV'
marchtwo_six = pd.read_csv(marchtwosix)

marchtwoseven= '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-27 Coronavirus Tweets.CSV'
marchtwo_seven = pd.read_csv(marchtwoseven)

marchtwoeight= '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-28 Coronavirus Tweets.CSV'
marchtwo_eight = pd.read_csv(marchtwoeight)

marchtwonine = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-29 Coronavirus Tweets.CSV'
marchtwo_nine = pd.read_csv(marchtwonine)

marchthreezero = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-30 Coronavirus Tweets.CSV'
marchthree_zero = pd.read_csv(marchthreezero)

marchthreeone = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-03-31 Coronavirus Tweets.CSV'
marchthree_one = pd.read_csv(marchthreeone)

aprone = '/content/drive/My Drive/Unstructured Project/coronavirus-covid19-tweets/2020-04-01 Coronavirus Tweets.CSV'
apr_one = pd.read_csv(aprone)

#combined all the data from all the days
corona_tweet = pd.concat([pre_march,marchone_two,marchone_three,marchone_four,marchone_five,marchone_six,marchone_seven,marchone_eight,marchone_nine,marchtwo_zero,marchtwo_one,marchtwo_two,marchtwo_three,marchtwo_four,marchtwo_five,marchtwo_six,marchtwo_seven,marchtwo_eight,marchtwo_nine,marchthree_zero,marchthree_one,apr_one])

#write to csv so my teammates won't have to run above everytime
corona_tweet.to_csv('combined_COVIDtweet.csv')



tweet_corona = '/content/drive/My Drive/Unstructured Project/combined_COVIDtweet.csv'
tweet_corona = pd.read_csv(tweet_corona)

tweet_corona.head()



tweet_corona.shape

tweet_corona = tweet_corona[tweet_corona['lang']=='en']